---
<%
director_uuid = "f3f0d625-18e1-48d1-9db4-b1be65d1cedc"    
protocol = "http"
cf_release = "169"
ip_address = "172.17.4.12"              
common_password = "c1oudc0w"
root_domain = "#{ip_address}.xip.io"
deployment_name = "cf-v169"
%>
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>
releases:
 - name: cf
   version: <%= cf_release %>
compilation:
  workers: 5             
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: compile     
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 4
networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
      - Allopen
resource_pools:
  - name: small
    network: default
    size: 16              
    stemcell:
      name: bosh-openstack-kvm-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.small  
  - name: medium
    network: default
    size: 0                
    stemcell:
      name: bosh-openstack-kvm-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.medium  
  - name: large
    network: default
    size: 1            
    stemcell:
      name: bosh-openstack-kvm-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.large  
jobs:
- instances: 1
  name: haproxy
  networks:
  - name: default
    default: [dns, gateway]
  - name: floating
    static_ips:
      - <%= ip_address %>
  resource_pool: small
  template: haproxy
- instances: 1
  name: nats
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: small
  template:
  - nats
  - nats_stream_forwarder
- instances: 1
  name: syslog_aggregator
  networks:
  - name: default
    default: [dns, gateway]
  persistent_disk: 8192
  resource_pool: small
  template: syslog_aggregator
- instances: 1
  name: collector
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: small
  template: collector
- instances: 1
  name: nfs
  networks:
  - name: default
    default: [dns, gateway]
  persistent_disk: 102400
  resource_pool: small
  template: debian_nfs_server
- instances: 1
  name: postgres
  networks:
  - name: default
    default: [dns, gateway]
  persistent_disk: 4096
  resource_pool: small
  template: postgres
- instances: 1
  name: uaa
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: small
  template: uaa
- instances: 1
  name: login
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: small
  template: login
- instances: 1
  name: ccng
  networks:
  - name: default
    default: [dns, gateway]
  persistent_disk: 0
  resource_pool: small
  template: cloud_controller_ng
- instances: 1
  name: ccng_clock
  networks:
  - name: default
    default: [dns, gateway]
  persistent_disk: 0
  resource_pool: small
  template: cloud_controller_ng
- instances: 1
  name: ccng_worker
  networks:
  - name: default
    default: [dns, gateway]
  persistent_disk: 0
  resource_pool: small
  template: cloud_controller_ng
- instances: 2
  name: etcd
  networks:
  - name: default
    default: [dns, gateway]
  persistent_disk: 10024
  resource_pool: small
  template: etcd
- instances: 1
  name: hm9000
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: small
  template: hm9000
- instances: 1
  name: dea
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: large
  template:
  - dea_next
  - dea_logging_agent
  update:
    max_in_flight: 1
- instances: 1
  name: loggregator
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: small
  template: loggregator
- instances: 1
  name: loggregator_trafficcontroller
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: small
  template: loggregator_trafficcontroller
- instances: 1
  name: router
  networks:
  - name: default
    default: [dns, gateway]
  resource_pool: small
  template: gorouter
properties:
  domain: <%= root_domain %>
  system_domain: <%= root_domain %>
  system_domain_organization: "demo"
  app_domains:
    - <%= root_domain %>
  support_address: http://support.<%= root_domain %>
  description: "Cloud Foundry v2 sponsored by Pivotal"

  networks:
    apps: default
    management: default

  ssl:
    skip_cert_verify: true

  etcd:
    machines: 
    - 192.168.100.4
    - 192.168.100.5      

  dea_next: {}

  logger_endpoint:
    shared_secret: c1oudc0w

  cc: &cc
    bulk_api_password: c1oudc0w
    srv_api_uri: http://api.<%= root_domain %>
    db_logging_level: debug2
    ccng.logging_level: debug2
    db_encryption_key: c1oudc0w
    quota_definitions:
      default:
        memory_limit: 10240
        total_services: 100
        non_basic_services_allowed: true
        total_routes: 1000
        trial_db_allowed: true
    hm9000_noop: false
    staging_upload_user: uploaduser
    staging_upload_password: c1oudc0w
    install_buildpacks:
      - name: java_buildpack
        package: buildpack_java
      - name: ruby_buildpack
        package: buildpack_ruby
      - name: nodejs_buildpack
        package: buildpack_nodejs
  ccng: *cc
  ccdb: &ccdb
    db_scheme: postgres
    address: 192.168.100.10
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: c1oudc0w
    databases:
      - tag: cc
        name: ccdb
        citext: true
  ccdb_ng: *ccdb

  uaadb:
    db_scheme: postgresql
    address: 192.168.100.10
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: c1oudc0w
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  databases:
    db_scheme: postgres
    address: 192.168.100.10
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: c1oudc0w
      - tag: admin
        name: uaaadmin
        password: c1oudc0w
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true
  db: databases

  collector:
    datadog_api_key: ""
    datadog_application_key: ""
    deployment_name: <%= deployment_name %>
    use_datadog: true
    use_tsdb: false
  disk_quota_enabled: true

  loggregator:
    status:
      user: loggregator
      password: c1oudc0w
      port: 5768
    incoming_port: 3456
    outgoing_port: 38080
    servers:
      default:
        - 192.168.100.17

  traffic_controller:
    zone: default
    status:
      user: trafic_controller
      password: c1oudc0w
      port: 6789
    incoming_port: 13456
    outgoing_port: 48080

  loggregator_endpoint: 
    shared_secret: c1oudc0w
    host: 192.168.100.18


  nats:
    address: 192.168.100.11
    machines: [ 192.168.100.11 ]
    debug: false
    password: c1oudc0w
    port: 4222
    trace: false
    use_gnatsd: true
    user: nats

  opentsdb: null
  request_timeout_in_seconds: 300
  router:
    servers:
      z1:
      - 192.168.100.19  
      z2: []    
    status:
      password: c1oudc0w
      user: router
  syslog_aggregator: 
    address: 192.168.100.13
    port: 54321

  uaa:
    login:
      addnew: false
    url: http://uaa.<%= root_domain %>
    catalina_opts: -Xmx384m -XX:MaxPermSize=256m
    no_ssl: true
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: c1oudc0w
    admin:
      client_secret: c1oudc0w
    batch:
      username: batch-username
      password: c1oudc0w
    clients: {}
    scim:
      users:
      - admin|c1oudc0w|scim.write,scim.read,openid,cloud_controller.admin
  login:
    brand: oss
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    links:
      home: http://console.<%= root_domain %>
      passwd: http://console.<%= root_domain %>/password_resets/new
      signup: http://console.<%= root_domain %>/register
    protocol: http
    uaa_certificate: null
  ha_proxy:
    ssl_pem: |
      -----BEGIN CERTIFICATE-----
      MIICLzCCAZgCCQCSoIG3LoeSMTANBgkqhkiG9w0BAQUFADBcMQswCQYDVQQGEwJV
      UzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xEDAOBgNVBAoT
      B1Bpdm90YWwxFjAUBgNVBAsTDUNsb3VkIEZvdW5kcnkwHhcNMTMxMDE3MjMxNzM5
      WhcNMTQxMDE3MjMxNzM5WjBcMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAU
      BgNVBAcTDVNhbiBGcmFuY2lzY28xEDAOBgNVBAoTB1Bpdm90YWwxFjAUBgNVBAsT
      DUNsb3VkIEZvdW5kcnkwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBANqyjJMH
      FDbJ4XM2vLRxz6i82Gd2Y2dnAKYgu67FgheHGQJSv38lvn8JrAOBXu2QJgP8sJa+
      XqUWUTMo9BWvhvedQLojtcpLdULc0FhlIXn8bThGlTQyrSg9QJobhQZGziFVrdQM
      UZy4X+s6A2Szb9iOg3TYibnnfnuvdZli83eRAgMBAAEwDQYJKoZIhvcNAQEFBQAD
      gYEAbFu65WT+czpiJqHhNz5AnGYA8kieVlV7KhcljLtsU4Sxut5Vq9uXFBE09KCg
      YkyZ9KfzXArTeRCfcbm5xq12I+1nf6q0QjT1y3P6ztax0rpyb0i+4GWvA+ruMhfx
      n4QM1MkiJVYBGKkXFZDd1zsdR3pY4vm1uiMY75IvJQfgb08=
      -----END CERTIFICATE-----
      -----BEGIN RSA PRIVATE KEY-----
      MIICXQIBAAKBgQDasoyTBxQ2yeFzNry0cc+ovNhndmNnZwCmILuuxYIXhxkCUr9/
      Jb5/CawDgV7tkCYD/LCWvl6lFlEzKPQVr4b3nUC6I7XKS3VC3NBYZSF5/G04RpU0
      Mq0oPUCaG4UGRs4hVa3UDFGcuF/rOgNks2/YjoN02Im55357r3WZYvN3kQIDAQAB
      AoGAa88G81fTBCtDA1vhbIaKWuE1QNOgrxGcxUhvnPlqZxTHJFkMY66EmPV4oYW9
      +RhNVTvVBYq092boAnNW1/Xebvrk1SnBDkrLntnGPmExkatOkPTFFlNXfePu6qOJ
      ULwYg8rKRwpvLoQXxbzMDXApPBifBNWGHVneGuHLpwPEQgECQQD0IJOecEyorrCR
      6+wmJBS/IwqQO0Ooj7kZEg65MHi9exVe+XFvP0lW2NAUsDuBLz79hjslSqIJjRG8
      c6q36oqhAkEA5VVeEip+T4DV12I5A5maGexVMeC92K7EGU/H8YhltxVZ/RtNngdT
      3r19WeDbDF7R5CJy2f7AYullk3S6fkk28QJBALdEiW1k4rezRMyW7tYHOifvN2vl
      gbpWAt/GRZVSxSGB+B4vZq/cM8NlynftgQ5PGJucnGQ3bgN7irgNoTimc2ECQFMX
      QBMy5DroAhKcmu2r/IKB90gwFnjosVI+bsIbWkcgbE9hUhj8rK2aWE11Q8hSnpea
      x6QmQgxUZiIr+9n/qvECQQDiDIeSmo2mRYsaqr4CQ3Ak+EDjsm9XTpXHuqm+xgFO
      iDIeQCWd3/twqdDTR7FaDE7Q0i559u7A1yLumUn8caLF
      -----END RSA PRIVATE KEY-----
  nfs_server:
    address: 192.168.100.6
    network: default
    idmapd_domain: dfw2

  debian_nfs_server:
    no_root_squash: true
